import type { CSSProperties } from "react";

/** Co-located styles for ProjectContextView (two-panel layout from the design). */
export const s = {
  layout: { display: "flex", height: "calc(100vh - 52px)" } satisfies CSSProperties,
  center: { flex: 1, display: "grid", placeItems: "center" } satisfies CSSProperties,
  left: {
    width: 234,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    borderRight: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  leftHead: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 8,
    padding: "16px 14px 12px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  leftHeadText: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  caps: {
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  repoName: {
    fontSize: 13,
    color: "var(--text-primary)",
    marginTop: 4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  list: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    padding: "8px",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  } satisfies CSSProperties,
  item: (active: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "9px 10px",
    borderRadius: 8,
    border: active ? "1px solid var(--border)" : "1px solid transparent",
    textAlign: "left",
    cursor: "pointer",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-secondary)",
  }),
  itemIcon: (active: boolean): CSSProperties => ({
    flexShrink: 0,
    color: active ? "var(--accent-text)" : "var(--text-muted)",
  }),
  itemText: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 2 } satisfies CSSProperties,
  itemName: {
    fontSize: 13,
    fontWeight: 500,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  itemDir: {
    fontSize: 11.5,
    color: "var(--text-muted)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  areaBadge: { flexShrink: 0, fontSize: 10.5, letterSpacing: "0.04em" } satisfies CSSProperties,
  notice: { padding: "8px 12px", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  footer: {
    padding: "12px 14px",
    borderTop: "1px solid var(--border)",
    fontSize: 11.5,
    color: "var(--text-muted)",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  footerLine: { display: "flex", alignItems: "center", gap: 6 } satisfies CSSProperties,
  dot: { width: 6, height: 6, borderRadius: 99, background: "var(--ok)" } satisfies CSSProperties,
  right: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column" } satisfies CSSProperties,
  rightHead: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "14px 24px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  fileName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  segmented: {
    display: "inline-flex",
    padding: 2,
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  segment: {
    padding: "3px 12px",
    borderRadius: 5,
    fontSize: 12,
    fontWeight: 600,
    background: "var(--bg-hover)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  usedBy: {
    marginLeft: "auto",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  content: { flex: 1, minHeight: 0, overflow: "auto", padding: "28px 28px" } satisfies CSSProperties,
  notice2: { margin: 0, fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
