import type { CSSProperties } from "react";

/** Co-located styles for FindingsSummary (PR-list Findings column + popover). */
export const s = {
  muted: { color: "var(--text-muted)", fontSize: 13 } satisfies CSSProperties,
  wrap: { position: "relative", display: "inline-block" } satisfies CSSProperties,
  trigger: {
    display: "inline-flex",
    alignItems: "center",
    gap: 4,
    padding: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
    font: "inherit",
    fontSize: 12.5,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    maxWidth: "100%",
  } satisfies CSSProperties,
  sep: { color: "var(--text-muted)" } satisfies CSSProperties,
  popover: {
    position: "absolute",
    top: "calc(100% + 6px)",
    left: 0,
    width: 320,
    background: "var(--bg-elevated)",
    border: "1px solid var(--border-strong)",
    borderRadius: 9,
    boxShadow: "var(--shadow-modal)",
    padding: 10,
    zIndex: 40,
    animation: "ddpop .12s ease",
  } satisfies CSSProperties,
  popoverHeader: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--text-secondary)",
    marginBottom: 8,
  } satisfies CSSProperties,
  popoverEmpty: { fontSize: 12.5, color: "var(--text-muted)", padding: "4px 2px" } satisfies CSSProperties,
  popoverList: { display: "flex", flexDirection: "column", gap: 4 } satisfies CSSProperties,
  popoverItem: {
    display: "flex",
    alignItems: "flex-start",
    gap: 8,
    width: "100%",
    padding: "6px 6px",
    borderRadius: 6,
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
  } satisfies CSSProperties,
  popoverItemMain: { minWidth: 0, flex: 1 } satisfies CSSProperties,
  popoverItemTitle: {
    fontSize: 12.5,
    fontWeight: 500,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  popoverItemMeta: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 11,
    color: "var(--text-muted)",
    marginTop: 2,
  } satisfies CSSProperties,
  popoverMore: { fontSize: 11.5, color: "var(--text-muted)", padding: "2px 6px" } satisfies CSSProperties,
  popoverFooterRow: {
    display: "flex",
    gap: 6,
    marginTop: 8,
    paddingTop: 8,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  popoverFooterChip: {
    padding: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
  } satisfies CSSProperties,
} as const;
