import type { CSSProperties } from "react";

/** Co-located styles for BlastRadiusCard (PR Brief "Blast radius" card, Tree view). */
const mono = { fontFamily: "var(--font-mono)" } satisfies CSSProperties;

export const s = {
  card: {
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
  } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, color: "var(--text-muted)" } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  statRow: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: 16 } satisfies CSSProperties,
  stat: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  statNum: { color: "var(--text-primary)", fontWeight: 700 } satisfies CSSProperties,
  toggle: {
    marginLeft: "auto",
    display: "inline-flex",
    padding: 2,
    gap: 2,
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-primary)",
  } satisfies CSSProperties,
  toggleBtn: (active: boolean): CSSProperties => ({
    fontSize: 12.5,
    padding: "3px 12px",
    borderRadius: 6,
    border: "1px solid transparent",
    background: active ? "var(--bg-hover)" : "transparent",
    color: active ? "var(--text-primary)" : "var(--text-muted)",
    fontWeight: active ? 600 : 400,
    cursor: active ? "default" : "pointer",
  }),
  notice: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    fontSize: 12.5,
    lineHeight: 1.45,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    borderRadius: 6,
    padding: "8px 10px",
  } satisfies CSSProperties,
  noticeTitle: { fontWeight: 700, marginRight: 6 } satisfies CSSProperties,
  muted: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.45 } satisfies CSSProperties,
  errorRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  tree: { display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  symbolRow: (open: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "8px 10px",
    border: "none",
    borderRadius: 6,
    background: open ? "var(--bg-hover)" : "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left",
  }),
  symbolName: { ...mono, fontSize: 13.5, fontWeight: 700 } satisfies CSSProperties,
  symbolIcon: { color: "var(--accent-text)", flexShrink: 0 } satisfies CSSProperties,
  callerCount: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  body: { display: "flex", flexDirection: "column", gap: 8, padding: "2px 0 6px 28px" } satisfies CSSProperties,
  callers: {
    listStyle: "none",
    margin: 0,
    padding: "0 0 0 10px",
    borderLeft: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  caller: { display: "flex", alignItems: "center", gap: 8, ...mono, fontSize: 12.5 } satisfies CSSProperties,
  /** Short horizontal tick joining each caller row to the vertical guide line (3.png). */
  callerTick: {
    flexShrink: 0,
    width: 10,
    marginLeft: -10,
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  callerLink: { color: "var(--text-secondary)", textDecoration: "none" } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  chip: (kind: "endpoint" | "cron"): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "3px 8px",
    borderRadius: 5,
    ...mono,
    fontSize: 12,
    background: kind === "cron" ? "var(--warn-bg)" : "var(--accent-bg)",
    color: kind === "cron" ? "var(--warn)" : "var(--accent-text)",
  }),
} as const;
