import type { CSSProperties } from "react";

/** Co-located styles for PriorPrs (3.png collapsed, 7.png / 10.png expanded). */
export const s = {
  wrap: { borderTop: "1px solid var(--border)", paddingTop: 14 } satisfies CSSProperties,
  box: {
    border: "1px solid var(--border)",
    borderRadius: 8,
    background: "var(--bg-primary)",
    overflow: "hidden",
  } satisfies CSSProperties,
  head: (open: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 10,
    width: "100%",
    padding: "12px 16px",
    border: "none",
    borderBottom: open ? "1px solid var(--border)" : "none",
    background: "transparent",
    color: "var(--text-primary)",
    cursor: "pointer",
    textAlign: "left",
  }),
  title: { fontSize: 14, fontWeight: 700 } satisfies CSSProperties,
  count: {
    fontSize: 12.5,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    borderRadius: 4,
    padding: "1px 7px",
  } satisfies CSSProperties,
  chevron: (open: boolean): CSSProperties => ({
    marginLeft: "auto",
    color: "var(--text-muted)",
    transform: open ? "rotate(180deg)" : "none",
  }),
  list: { listStyle: "none", margin: 0, padding: 0 } satisfies CSSProperties,
  item: (first: boolean): CSSProperties => ({
    position: "relative",
    padding: "14px 16px 14px 40px",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    borderTop: first ? "none" : "1px solid var(--border)",
  }),
  dot: {
    position: "absolute",
    left: 18,
    top: 21,
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: "var(--text-muted)",
  } satisfies CSSProperties,
  line: {
    position: "absolute",
    left: 20,
    top: 34,
    bottom: 14,
    width: 1,
    background: "var(--border)",
  } satisfies CSSProperties,
  row1: { display: "flex", alignItems: "baseline", gap: 10 } satisfies CSSProperties,
  num: {
    fontFamily: "var(--font-mono)",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-text)",
    textDecoration: "none",
  } satisfies CSSProperties,
  prTitle: { fontSize: 14, fontWeight: 700, color: "var(--text-primary)" } satisfies CSSProperties,
  byline: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    fontSize: 12.5,
    color: "var(--text-muted)",
    paddingLeft: 10,
  } satisfies CSSProperties,
  note: {
    fontSize: 13.5,
    lineHeight: 1.5,
    color: "var(--text-secondary)",
    margin: 0,
    paddingLeft: 10,
  } satisfies CSSProperties,
} as const;
