import type { CSSProperties } from "react";

/** Co-located styles for ContextDocList. */
export const s = {
  header: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700, margin: 0 } satisfies CSSProperties,
  count: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "2px 10px",
    borderRadius: 999,
  } satisfies CSSProperties,
  filter: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "6px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    width: 260,
  } satisfies CSSProperties,
  filterIcon: { color: "var(--text-muted)" } satisfies CSSProperties,
  filterInput: {
    flex: 1,
    minWidth: 0,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-secondary)", margin: "10px 0 16px" } satisfies CSSProperties,
  notice: { fontSize: 13, color: "var(--text-muted)", padding: "8px 0" } satisfies CSSProperties,
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (dragging: boolean, attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: attached ? "var(--bg-elevated)" : "var(--bg-surface)",
    opacity: dragging ? 0.4 : 1,
  }),
  handle: (draggable: boolean): CSSProperties => ({
    cursor: draggable ? "grab" : "default",
    color: "var(--text-muted)",
    display: "inline-flex",
    opacity: draggable ? 1 : 0.5,
  }),
  nameWrap: { flex: 1, minWidth: 0, display: "flex", alignItems: "baseline", gap: 10, overflow: "hidden" } satisfies CSSProperties,
  name: (attached: boolean): CSSProperties => ({
    fontSize: 14,
    fontWeight: attached ? 600 : 500,
    color: attached ? "var(--text-primary)" : "var(--text-secondary)",
    whiteSpace: "nowrap",
    flexShrink: 0,
  }),
  dir: {
    fontSize: 12,
    color: "var(--text-muted)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    minWidth: 0,
  } satisfies CSSProperties,
  marker: { fontSize: 12, color: "var(--warn)", whiteSpace: "nowrap" } satisfies CSSProperties,
  typeBadge: { textTransform: "none", padding: "2px 8px" } satisfies CSSProperties,
  moveBtn: {
    display: "inline-grid",
    placeItems: "center",
    width: 24,
    height: 24,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "transparent",
    color: "var(--text-muted)",
    cursor: "pointer",
    padding: 0,
  } satisfies CSSProperties,
  previewBtn: (withText: boolean): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: withText ? "5px 12px" : "5px 9px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-surface)",
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
  }),
  footer: {
    marginTop: 20,
    paddingTop: 14,
    borderTop: "1px solid var(--border)",
    display: "flex",
    justifyContent: "space-between",
    gap: 16,
    fontSize: 12.5,
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tokens: { color: "var(--text-secondary)" } satisfies CSSProperties,
  checkbox: (checked: boolean): CSSProperties => ({
    appearance: "none",
    WebkitAppearance: "none",
    width: 16,
    height: 16,
    margin: 0,
    flexShrink: 0,
    borderRadius: 4,
    cursor: "pointer",
    border: "1.5px solid " + (checked ? "var(--accent)" : "var(--border-strong)"),
    backgroundColor: checked ? "var(--accent)" : "var(--bg-surface)",
    backgroundImage: checked ? CHECK_ICON : "none",
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "11px 11px",
  }),
} as const;

/** White tick drawn as the checked checkbox background (same as the agent SkillsTab). */
const CHECK_ICON =
  "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='white' stroke-width='3.5' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpath d='M5 12.5l4.5 4.5L19 7.5'/%3E%3C/svg%3E\")";
