import type { CSSProperties } from "react";

/** Co-located styles for IntentCard (follows the PR Brief "Intent" card design). */
export const s = {
  card: (dimmed: boolean): CSSProperties => ({
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--bg-elevated)",
    padding: 18,
    display: "flex",
    flexDirection: "column",
    gap: 14,
    opacity: dimmed ? 0.6 : 1,
  }),
  header: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  tag: (color: string): CSSProperties => ({
    fontSize: 11.5,
    color,
    border: "1px solid var(--border)",
    borderRadius: 4,
    padding: "1px 6px",
  }),
  action: { marginLeft: "auto", display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  quote: {
    fontSize: 14,
    fontStyle: "italic",
    lineHeight: 1.5,
    color: "var(--text-primary)",
    margin: 0,
  } satisfies CSSProperties,
  columns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 } satisfies CSSProperties,
  colTitle: (color: string): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    color,
    marginBottom: 8,
  }),
  list: { listStyle: "none", margin: 0, padding: 0, display: "flex", flexDirection: "column", gap: 6 } satisfies CSSProperties,
  item: (color: string): CSSProperties => ({
    display: "flex",
    alignItems: "flex-start",
    gap: 6,
    fontSize: 12.5,
    lineHeight: 1.4,
    color,
  }),
  bullet: { flexShrink: 0, color: "var(--text-muted)", lineHeight: 1.4 } satisfies CSSProperties,
  chips: { display: "flex", flexWrap: "wrap", gap: 8 } satisfies CSSProperties,
  chip: {
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "4px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    fontSize: 12.5,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  muted: { fontSize: 12.5, color: "var(--text-muted)", lineHeight: 1.45 } satisfies CSSProperties,
  skeletons: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
} as const;
